apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: flask-vault-example
  name: flask-vault-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-vault-example
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flask-vault-example
    spec:
      containers:
      - image: gcr.io/nutresa-165613/flask-vault-example:latest
        imagePullPolicy: Always
        name: flask-vault-example
        resources: {}
status: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: flask-vault-example
  name: flask-vault-example
  namespace: default
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: flask-vault-example
  type: LoadBalancer